# Generated by Django 4.1.2 on 2022-11-15 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Пост с категориями', 'verbose_name_plural': 'Посты с категориями'},
        ),
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user_rate',
            field=models.IntegerField(default=0, verbose_name='Рейтинг автора'),
        ),
        migrations.AlterField(
            model_name='category',
            name='article_category',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_rate',
            field=models.IntegerField(default=0, verbose_name='Рэйтинг комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='feedback_text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('A', 'Статья'), ('N', 'Новость')], default='N', max_length=1, verbose_name='Тип поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='текст поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(to='news.category', verbose_name='Категория поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_rate',
            field=models.IntegerField(default=0, verbose_name='Рейтинг поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название поста'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='category_category',
            field=models.ManyToManyField(to='news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='post_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Пост'),
        ),
    ]
